import React, { Component } from 'react';
import Header from './components/Header'
import Grid from './components/Grid'
import Form from './components/Form'

// JSX allows us to insert any kind of JS (functions, variables etc)

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      notes: [
        {
          id: 1,
          title: 'Add course notes for ML class',
          details: 'Submit How to use ensemble learning to improve predictions'
        },
        {
          id: 2,
          title: 'Setup Trello board',
          details: 'To track personal committments'
        },
        {
          id: 3,
          title: 'Submit Kaggle Zillow competition predictions',
          details: 'Scores generated by model'
        },
    ],
      name: 'Armen',
      currentTitle: '',
      currentDetails: '',
    }
  }

  handleChange(event){
    const name = event.target.name;
    const value = event.target.value;

    this.setState({
      [name]: value
    });
  }

  handleSubmit(event){
    alert(`Your note ${this.state.currentTitle} has been added successfully`);
    event.preventDefault();
  }

  render() {
    return (
      <div className="App">
        <Header name={this.state.name}/>
        <Form 
          currentTitle = {this.state.currentTitle}
          currentDetails = {this.state.currentDetails}
          handleChange={this.state.handleChange}
          handleSubmit={this.state.handleSubmit}
          />
        <Grid notes = {this.state.notes}/>
      </div>

    );
  }
}

export default App;
